import{createClient}from'https://esm.sh/@supabase/supabase-js@2';
const cors={'Access-Control-Allow-Origin':'https://zuquicafe.com.br','Access-Control-Allow-Headers':'authorization,content-type','Access-Control-Allow-Methods':'POST,OPTIONS','Content-Type':'application/json'};const out=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:cors});
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return out({error:'Método não permitido'},405);const url=Deno.env.get('SUPABASE_URL')!,anon=Deno.env.get('SUPABASE_ANON_KEY')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,db=createClient(url,service,{auth:{persistSession:false}}),body=await req.json().catch(()=>({})),action=String(body.action||'');
try{
if(action==='public_menu'){const[{data:categories},{data:products},{data:cards},{data:references},{data:settings}]=await Promise.all([db.from('menu_categories').select('*').eq('available',true).order('sort_order'),db.from('menu_products').select('*').eq('available',true).order('sort_order'),db.from('menu_cards').select('id,label,available,sort_order').eq('available',true).order('sort_order'),db.from('menu_references').select('*').eq('available',true).order('sort_order'),db.from('menu_settings').select('*').single()]);return out({categories,products,cards,references,ordering_enabled:!!settings?.ordering_enabled})}
if(action==='login'){if(String(body.username).toLowerCase()!=='admin')return out({error:'Credenciais inválidas'},401);const auth=createClient(url,anon,{auth:{persistSession:false}}),email=Deno.env.get('CARDAPIO_ADMIN_EMAIL');if(!email)throw new Error('Administrador ainda não configurado.');const{data,error}=await auth.auth.signInWithPassword({email,password:String(body.password||'')});if(error||!data.session)return out({error:'Credenciais inválidas'},401);const{data:profile}=await db.from('menu_admin_profiles').select('must_change_password').eq('user_id',data.user.id).single();return out({access_token:data.session.access_token,must_change_password:!!profile?.must_change_password})}
const bearer=req.headers.get('authorization')?.replace(/^Bearer\s+/i,'');if(!bearer)return out({error:'Sessão obrigatória'},401);const{data:{user}}=await db.auth.getUser(bearer);if(!user)return out({error:'Sessão inválida'},401);const{data:profile}=await db.from('menu_admin_profiles').select('*').eq('user_id',user.id).single();if(!profile)return out({error:'Acesso negado'},403);
if(action==='change_password'){if(String(body.password||'').length<12)return out({error:'Use pelo menos 12 caracteres.'},400);const{error}=await db.auth.admin.updateUserById(user.id,{password:String(body.password)});if(error)throw error;await db.from('menu_admin_profiles').update({must_change_password:false}).eq('user_id',user.id);return out({ok:true})}if(profile.must_change_password)return out({error:'Troque a senha inicial antes de continuar.'},403);
if(action==='admin_snapshot'){const names=['categories','products','cards','references','orders'] as const,res:any={};for(const n of names){const table=n==='categories'?'menu_categories':n==='products'?'menu_products':n==='cards'?'menu_cards':n==='references'?'menu_references':'menu_orders';const{data}=await db.from(table).select('*').order(n==='orders'?'created_at':'sort_order',{ascending:n!=='orders'}).limit(n==='orders'?100:500);res[n]=data||[]}const{data:i}=await db.from('menu_integration').select('endpoint_url,http_method,auth_type,notes').single(),{data:s}=await db.from('menu_settings').select('*').single();return out({...res,integration:{...i,ready:!!(i?.endpoint_url&&i?.http_method&&i?.auth_type),test_validated:!!s?.test_validated},ordering_enabled:!!s?.ordering_enabled})}
if(action==='upsert_entity'){const map:any={category:'menu_categories',product:'menu_products',card:'menu_cards',reference:'menu_references'},table=map[body.kind];if(!table)return out({error:'Entidade inválida'},400);const row={...body};delete row.action;delete row.kind;if(!row.id)delete row.id;if(body.kind==='card'){row.label=row.label||row.name;row.virtual_code=row.virtual_code||row.label;delete row.name}else{row.name=row.name||row.label;delete row.label}if(body.kind!=='product')for(const k of['description','price','image_url','category_id'])delete row[k];const{error}=await db.from(table).upsert(row);if(error)throw error;return out({ok:true})}
if(action==='save_integration'){await db.from('menu_integration').update({endpoint_url:body.endpoint_url||null,http_method:body.http_method||null,auth_type:body.auth_type||null,notes:body.notes||null,updated_at:new Date().toISOString()}).eq('id',true);return out({ok:true})}
if(action==='set_ordering'){const{data:s}=await db.from('menu_settings').select('test_validated').single();if(body.enabled&&!s?.test_validated)return out({error:'O teste da comanda 4 ainda não foi validado.'},409);await db.from('menu_settings').update({ordering_enabled:!!body.enabled}).eq('id',true);return out({ok:true})}
if(action==='create_order')return out({error:'Envio público permanece bloqueado até validação da integração.'},503);
if(action==='test_order'){const{data:i}=await db.from('menu_integration').select('*').single();if(!i?.endpoint_url||!i?.http_method||!i?.auth_type)return out({error:'Complete URL, método e autenticação antes do teste.'},409);const now=new Date().toISOString(),guid=crypto.randomUUID(),payload={isOldOrder:false,identificador:guid,idgarcom:20,setorimpressao:'Nenhum',pedido:{nomereferencia:'MESA 04',itens:[{idproduto:451,nomereduzido:'ACHOCOLATADO CHOCO LEITE 208ML',valor:6.7,valorvariacao:null,arvore:'2.1',unidademedida:'UN',codigobarra:'7896060506483',observacao:'',permitevendafracionada:false,quantidade:1,idgarcom:20,valorunitario:6.7,datahora:now,valortotal:6.7}],ocupantes:1,datahora:now},cartaoconsumo:{nomecliente:'4',codigovirtual:'4'}};const{data:o,error}=await db.from('menu_orders').insert({guid,card_label:'4',reference_name:'MESA 04',status:'sending',request_payload:payload}).select().single();if(error)throw error;const secret=Deno.env.get('RAFFINATO_AUTH_VALUE'),header=Deno.env.get('RAFFINATO_AUTH_HEADER');const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);try{const headers:any={'content-type':'application/json'};if(header&&secret)headers[header]=secret;const r=await fetch(i.endpoint_url,{method:i.http_method,headers,body:JSON.stringify(payload),signal:controller.signal});clearTimeout(timer);const response=await r.json().catch(()=>({raw_response:true})),success=r.ok&&response.gravado===true,status=success?'success':'failed';await db.from('menu_orders').update({status,response_payload:response,http_status:r.status,idvenda:response.idvenda||null,numeropedido:response.numeropedido||null,error_message:success?null:'Resposta não confirmou gravado: true',sent_at:new Date().toISOString()}).eq('id',o.id);if(success)await db.from('menu_settings').update({test_validated:true}).eq('id',true);return out({status,message:success?'Pedido gravado com sucesso.':'API não confirmou a gravação.',guid})}catch(e){clearTimeout(timer);const uncertain=e?.name==='AbortError';await db.from('menu_orders').update({status:uncertain?'uncertain':'failed',error_message:uncertain?'Timeout: resultado incerto; confira o log antes de reenviar.':String(e),sent_at:new Date().toISOString()}).eq('id',o.id);return out({status:uncertain?'uncertain':'failed',message:uncertain?'Não reenvie automaticamente. Confira o Raffinato e o log.':String(e),guid},uncertain?504:502)}}
return out({error:'Ação desconhecida'},404)}catch(e){console.error(e);return out({error:'Falha interna segura.'},500)}});
