const cfg=window.ZUQUI_CARDAPIO_CONFIG||{},money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}),params=new URLSearchParams(location.search);
let data={categories:[],products:[],references:[],ordering_enabled:false},cart=new Map(JSON.parse(localStorage.getItem('zuqui_cart')||'[]')),active='',cardClaim=params.get('claim')||sessionStorage.getItem('zuqui_card_claim')||'';
if(params.get('claim'))sessionStorage.setItem('zuqui_card_claim',cardClaim);
async function api(action,body={}){if(!cfg.apiUrl)throw new Error('Cardápio ainda não conectado ao servidor.');const r=await fetch(cfg.apiUrl,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,...body})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Falha ao acessar o cardápio.');return j}
const publicApiRequest=api;
api=async function(action,body={}){const result=await publicApiRequest(action,body);if(action==='public_menu'){result.categories=(result.categories||[]).map(x=>({...x,name:x.display_name||x.name}));result.products=(result.products||[]).map(x=>({...x,name:x.display_name||x.name}))}return result};
const $=id=>document.getElementById(id),escape=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function render(){const cats=data.categories.filter(x=>x.available!==false);$('categories').innerHTML=`<button class="${!active?'active':''}" data-cat="">Todos</button>`+cats.map(x=>`<button class="${active===x.id?'active':''}" data-cat="${x.id}">${escape(x.name)}</button>`).join('');const products=data.products.filter(x=>x.available&&(!active||x.category_id===active));$('products').innerHTML=products.length?products.map(p=>`<article class="product">${p.image_url?`<img src="${escape(p.image_url)}" alt="">`:'<div></div>'}<div class="product-body"><h3>${escape(p.name)}</h3><p>${escape(p.description)}</p><div class="product-foot"><strong>${money.format(p.price)}</strong><button data-add="${p.id}">+</button></div></div></article>`).join(''):'<div class="empty">Nenhum produto disponível.</div>';$('referenceSelect').innerHTML='<option value="">Selecione</option>'+data.references.filter(x=>x.available).map(x=>`<option value="${x.id}">${escape(x.name)}</option>`).join('');const savedRef=params.get('reference')||localStorage.getItem('zuqui_reference');if(savedRef&&data.references.some(x=>x.id===savedRef)){$('referenceSelect').value=savedRef;localStorage.setItem('zuqui_reference',savedRef)}$('cardClaimStatus').textContent=cardClaim?'QR seguro da comanda reconhecido neste aparelho.':'Para finalizar, leia o segundo QR fixado na comanda do PDV.';$('notice').textContent=data.ordering_enabled?'':'Cardápio em preparação. Os pedidos públicos ainda não estão habilitados.';renderCart()}
function renderCart(){let count=0,total=0;$('cartItems').innerHTML=[...cart.values()].map(x=>{count+=x.qty;total+=x.qty*x.price;return `<div class="cart-item"><div><strong>${escape(x.name)}</strong><br><small>${money.format(x.price)}</small></div><div class="qty"><button data-dec="${x.id}">−</button><b>${x.qty}</b><button data-add="${x.id}">+</button></div></div>`}).join('')||'<p class="empty">Seu pedido está vazio.</p>';$('cartCount').textContent=count;$('cartTotal').textContent=money.format(total);localStorage.setItem('zuqui_cart',JSON.stringify([...cart]))}
document.addEventListener('click',e=>{const add=e.target.closest('[data-add]'),dec=e.target.closest('[data-dec]'),cat=e.target.closest('[data-cat]');if(add){const p=data.products.find(x=>x.id===add.dataset.add),old=cart.get(p.id)||{...p,qty:0};old.qty++;cart.set(p.id,old);renderCart()}if(dec){const x=cart.get(dec.dataset.dec);if(x&&--x.qty<=0)cart.delete(x.id);renderCart()}if(cat){active=cat.dataset.cat;render()}});
function toggle(open){$('cart').classList.toggle('open',open);$('overlay').classList.toggle('open',open);$('cart').setAttribute('aria-hidden',String(!open))}$('cartButton').onclick=()=>toggle(true);$('closeCart').onclick=$('overlay').onclick=()=>toggle(false);
$('referenceSelect').onchange=e=>localStorage.setItem('zuqui_reference',e.target.value);
$('reviewButton').onclick=()=>{const ref=$('referenceSelect').selectedOptions[0];if(!cart.size||!cardClaim||!ref.value){$('cartMessage').textContent=!cardClaim?'Leia o QR seguro da comanda para finalizar.':'Escolha itens e o ponto de referência.';return}$('reviewContent').innerHTML=`<p><b>Comanda:</b> validada pelo QR seguro<br><b>Referência:</b> ${escape(ref.textContent)}</p>`+[...cart.values()].map(x=>`<p>${x.qty}× ${escape(x.name)} — ${money.format(x.qty*x.price)}</p>`).join('')+`<hr><b>${$('cartTotal').textContent}</b>`;$('reviewDialog').showModal()};
$('backButton').onclick=()=>$('reviewDialog').close();
$('confirmButton').onclick=async()=>{if(!data.ordering_enabled){$('reviewMessage').textContent='Pedidos reais ainda não foram ativados pelo administrador.';return}try{$('confirmButton').disabled=true;const result=await api('create_order',{card_claim:cardClaim,reference_id:$('referenceSelect').value,note:$('orderNote').value,items:[...cart.values()].map(x=>({product_id:x.id,quantity:x.qty}))});$('reviewMessage').textContent=`Pedido recebido. Código ${result.guid}.`;cart.clear();renderCart()}catch(e){$('reviewMessage').textContent=e.message}finally{$('confirmButton').disabled=false}};
(async()=>{try{data=await api('public_menu');render()}catch(e){$('notice').textContent=e.message;$('products').innerHTML='<div class="empty">A configuração segura do cardápio está pendente.</div>'}})();
