import { BrowserQRCodeReader } from 'https://esm.sh/@zxing/browser@0.1.5';

const cfg=window.ZUQUI_CARDAPIO_CONFIG||{},money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}),params=new URLSearchParams(location.search),$=id=>document.getElementById(id),escape=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let data={categories:[],products:[],references:[],ordering_enabled:false},cart=new Map(JSON.parse(localStorage.getItem('zuqui_cart')||'[]')),active='',cardClaim=params.get('claim')||sessionStorage.getItem('zuqui_card_claim')||'',referenceId=params.get('reference')||'',scannerControls=null,reviewAfterScan=false;
if(params.get('claim'))sessionStorage.setItem('zuqui_card_claim',cardClaim);
async function api(action,body={}){if(!cfg.apiUrl)throw new Error('Cardápio ainda não conectado ao servidor.');const r=await fetch(cfg.apiUrl,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,...body})}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Falha ao acessar o cardápio.');if(action==='public_menu'){j.categories=(j.categories||[]).map(x=>({...x,name:x.display_name||x.name}));j.products=(j.products||[]).map(x=>({...x,name:x.display_name||x.name}))}return j}
function reference(){return data.references.find(x=>x.id===referenceId&&x.available)}
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.remove('show'),1800)}
function render(){const cats=data.categories.filter(x=>x.available!==false),ref=reference();$('categories').innerHTML=`<button class="${!active?'active':''}" data-cat="">Todos</button>`+cats.map(x=>`<button class="${active===x.id?'active':''}" data-cat="${x.id}">${escape(x.name)}</button>`).join('');const products=data.products.filter(x=>x.available&&(!active||x.category_id===active));$('products').innerHTML=products.length?products.map(p=>`<article class="product">${p.image_url?`<img src="${escape(p.image_url)}" alt="">`:'<div class="product-placeholder"></div>'}<div class="product-body"><h3>${escape(p.name)}</h3><p>${escape(p.description)}</p><div class="product-foot"><strong>${money.format(p.source_price??p.price)}</strong><button data-add="${p.id}" aria-label="Adicionar ${escape(p.name)}">+</button></div></div></article>`).join(''):'<div class="empty">Nenhum produto disponível.</div>';$('tableStatus').innerHTML=ref?`<span>Pedido para</span><strong>${escape(ref.name)}</strong>`:'<strong>Leia o QR da mesa para iniciar o pedido</strong>';$('fixedReference').textContent=ref?ref.name:'Mesa não identificada';$('notice').textContent=data.ordering_enabled?'':'Cardápio em preparação. Os pedidos públicos ainda não estão habilitados.';renderCart()}
function renderCart(){let count=0,total=0;$('cartItems').innerHTML=[...cart.values()].map(x=>{count+=x.qty;total+=x.qty*x.price;return `<div class="cart-item"><div><strong>${escape(x.name)}</strong><br><small>${money.format(x.price)}</small></div><div class="qty"><button data-dec="${x.id}" aria-label="Remover um">−</button><b>${x.qty}</b><button data-add="${x.id}" aria-label="Adicionar um">+</button></div></div>`}).join('')||'<p class="empty">Seu carrinho está vazio.</p>';$('cartCount').textContent=count;$('cartHeaderTotal').textContent=money.format(total);$('cartTotal').textContent=money.format(total);$('cartButton').classList.toggle('has-items',count>0);$('cardClaimBox').classList.toggle('validated',!!cardClaim);$('cardClaimStatus').textContent=cardClaim?'Comanda lida e validada neste aparelho.':'A comanda controla separadamente o seu consumo.';$('scanCard').textContent=cardClaim?'Ler outra comanda':'Abrir câmera e ler comanda';localStorage.setItem('zuqui_cart',JSON.stringify([...cart]))}
document.addEventListener('click',e=>{const add=e.target.closest('[data-add]'),dec=e.target.closest('[data-dec]'),cat=e.target.closest('[data-cat]');if(add){const p=data.products.find(x=>x.id===add.dataset.add);if(!p)return;const old=cart.get(p.id)||{...p,price:Number(p.source_price??p.price),qty:0};old.qty++;cart.set(p.id,old);renderCart();toast(`${old.qty} × ${p.name} no carrinho`)}if(dec){const x=cart.get(dec.dataset.dec);if(x&&--x.qty<=0)cart.delete(x.id);renderCart()}if(cat){active=cat.dataset.cat;render()}});
function toggle(open){$('cart').classList.toggle('open',open);$('overlay').classList.toggle('open',open);$('cart').setAttribute('aria-hidden',String(!open))}$('cartButton').onclick=()=>toggle(true);$('closeCart').onclick=$('overlay').onclick=()=>toggle(false);
function acceptClaim(raw){let token='';try{const u=new URL(raw,location.origin);token=u.searchParams.get('claim')||''}catch{}if(!token&&/^[a-f0-9]{64}$/i.test(raw.trim()))token=raw.trim();if(!token)throw new Error('Este QR não é uma comanda válida do Zuqui.');cardClaim=token;sessionStorage.setItem('zuqui_card_claim',token);renderCart();stopScanner();toast('Comanda lida com sucesso');if(reviewAfterScan){reviewAfterScan=false;showReview()}else toggle(true)}
async function startScanner(continueReview=false){reviewAfterScan=continueReview;$('scannerDialog').showModal();$('scannerMessage').textContent='Abrindo câmera…';try{const reader=new BrowserQRCodeReader();scannerControls=await reader.decodeFromVideoDevice(undefined,$('scannerVideo'),result=>{if(result)try{acceptClaim(result.getText())}catch(e){$('scannerMessage').textContent=e.message}});$('scannerMessage').textContent='Câmera ativa. Aponte para o QR da comanda.'}catch{$('scannerMessage').textContent='Não foi possível abrir a câmera. Permita o acesso ou escolha uma foto do QR.'}}
function stopScanner(){scannerControls?.stop();scannerControls=null;$('scannerVideo').srcObject?.getTracks().forEach(t=>t.stop());if($('scannerDialog').open)$('scannerDialog').close()}
$('scanCard').onclick=()=>startScanner(false);$('closeScanner').onclick=stopScanner;$('scannerDialog').addEventListener('close',()=>{scannerControls?.stop();scannerControls=null});$('qrImage').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;const url=URL.createObjectURL(file);try{const result=await new BrowserQRCodeReader().decodeFromImageUrl(url);acceptClaim(result.getText())}catch{$('scannerMessage').textContent='Não foi possível reconhecer o QR nesta imagem.'}finally{URL.revokeObjectURL(url)}};
function showReview(){const ref=reference();$('reviewContent').innerHTML=`<p><b>Comanda:</b> validada pelo QR seguro<br><b>Entrega:</b> ${escape(ref.name)}</p>`+[...cart.values()].map(x=>`<p>${x.qty}× ${escape(x.name)} — ${money.format(x.qty*x.price)}</p>`).join('')+`<hr><b>${$('cartTotal').textContent}</b>`;$('reviewDialog').showModal()}
$('reviewButton').onclick=()=>{const ref=reference();if(!ref){$('cartMessage').textContent='Abra o cardápio pelo QR da mesa para definir o local da entrega.';return}if(!cart.size){$('cartMessage').textContent='Adicione pelo menos um produto ao carrinho.';return}if(!cardClaim){$('cartMessage').textContent='Leia o QR da sua comanda para finalizar.';startScanner(true);return}$('cartMessage').textContent='';showReview()};
$('backButton').onclick=()=>$('reviewDialog').close();$('confirmButton').onclick=async()=>{if(!data.ordering_enabled){$('reviewMessage').textContent='Pedidos reais ainda não foram ativados pelo administrador.';return}try{$('confirmButton').disabled=true;const result=await api('create_order',{card_claim:cardClaim,reference_id:referenceId,note:$('orderNote').value,items:[...cart.values()].map(x=>({product_id:x.id,quantity:x.qty}))});$('reviewMessage').textContent=`Pedido recebido. Código ${result.guid}.`;cart.clear();renderCart()}catch(e){$('reviewMessage').textContent=e.message}finally{$('confirmButton').disabled=false}};
(async()=>{try{data=await api('public_menu');render()}catch(e){$('notice').textContent=e.message;$('products').innerHTML='<div class="empty">Não foi possível carregar o cardápio agora.</div>'}})();
