const cfg=window.ZUQUI_CARDAPIO_CONFIG||{},money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}),params=new URLSearchParams(location.search),$=id=>document.getElementById(id),escape=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let data={categories:[],products:[],references:[],ordering_enabled:false},cart=new Map(JSON.parse(localStorage.getItem('zuqui_cart')||'[]')),active='',cardClaim=sessionStorage.getItem('zuqui_card_claim')||'',cardLabel=sessionStorage.getItem('zuqui_card_label')||'',referenceId=params.get('reference')||'',scannerControls=null,afterScan=null,sending=false,qrReaderClass=null,failedOrders=new Map();
let editingNoteId='';
async function api(action,body={}){if(!cfg.apiUrl)throw new Error('Cardápio ainda não conectado ao servidor.');const r=await fetch(cfg.apiUrl,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,...body})}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Falha ao acessar o cardápio.');if(action==='public_menu'){j.categories=(j.categories||[]).map(x=>({...x,name:x.display_name||x.name}));j.products=(j.products||[]).map(x=>({...x,name:x.display_name||x.name}))}return j}
const apiBase=api;api=async function(action,body={}){if(action==='create_order')body={...body,items:[...cart.values()].map(x=>({product_id:x.id,quantity:x.qty,observation:String(x.observation||'').slice(0,200)}))};return apiBase(action,body)};
function reference(){return data.references.find(x=>x.id===referenceId&&x.available)}
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.remove('show'),2200)}
function updateIdentity(){const ready=!!cardClaim;$('callWaiterButton').disabled=!ready;$('accountButton').disabled=!ready;$('welcome').classList.toggle('identified',ready);$('welcomeTitle').textContent=ready?`Comanda ${cardLabel} identificada`:'Leia sua comanda';$('welcomeCopy').textContent=ready?'Agora você pode lançar pedidos, acompanhar sua conta digital e pedir atendimento.':'Leia o QR da comanda uma vez para lançar pedidos, acompanhar seus lançamentos digitais ou chamar um atendente.';$('identifyCardButton').textContent=ready?'Trocar comanda':'Ler QR da comanda';$('cardClaimBox').classList.toggle('validated',ready);$('cardClaimBox').querySelector('strong').textContent=ready?`COMANDA ${cardLabel}`:'IDENTIFIQUE SUA COMANDA';$('cardClaimBox').querySelector('p').textContent=ready?'Pronta para receber este lançamento.':'Leia o QR para lançar o pedido com segurança.';$('scanFromCart').hidden=ready}
function render(){const cats=data.categories.filter(x=>x.available!==false),ref=reference(),current=cats.find(x=>x.id===active);$('categories').innerHTML=`<button class="${!active?'active':''}" data-cat=""><span>Todos</span><small>${data.products.filter(x=>x.available).length}</small></button>`+cats.map(x=>`<button class="${active===x.id?'active':''}" data-cat="${x.id}"><span>${escape(x.name)}</span><small>${data.products.filter(p=>p.available&&p.category_id===x.id).length}</small></button>`).join('');const products=data.products.filter(x=>x.available&&(!active||x.category_id===active));$('categoryTitle').textContent=current?.name||'Todos os produtos';$('products').innerHTML=products.length?products.map(p=>`<article class="product">${p.image_url?`<img src="${escape(p.image_url)}" alt="${escape(p.name)}" loading="lazy">`:'<div class="product-placeholder" aria-hidden="true"></div>'}<div class="product-body"><h3>${escape(p.name)}</h3><p>${escape(p.description)}</p><div class="product-foot"><strong>${money.format(p.source_price??p.price)}</strong><button data-add="${p.id}" aria-label="Adicionar ${escape(p.name)}">Adicionar</button></div></div></article>`).join(''):'<div class="empty">Nenhum produto disponível neste setor.</div>';$('tableStatus').innerHTML=ref?`<span>Entrega em</span><strong>${escape(ref.name)}</strong>`:'<span>Mesa</span><strong>não identificada</strong>';$('fixedReference').textContent=ref?ref.name:'Mesa não identificada';$('notice').textContent=data.ordering_enabled?'':'Cardápio em preparação. Os pedidos públicos ainda não estão habilitados.';renderCart();updateIdentity()}
function renderCart(){let count=0,total=0;$('cartItems').innerHTML=[...cart.values()].map(x=>{count+=x.qty;total+=x.qty*x.price;const note=String(x.observation||'');return `<div class="cart-item"><div class="cart-item-copy"><strong>${escape(x.name)}</strong><small>${money.format(x.price)}</small>${note?`<em>${escape(note)}</em>`:''}</div><button class="item-note ${note?'has-note':''}" data-item-note="${x.id}" aria-label="${note?'Editar':'Adicionar'} observação em ${escape(x.name)}"><span aria-hidden="true">💬</span><small>${note?'Editar':'Observação'}</small></button><div class="qty"><button data-dec="${x.id}" aria-label="Remover um">−</button><b>${x.qty}</b><button data-add="${x.id}" aria-label="Adicionar um">+</button></div></div>`}).join('')||'<p class="empty">Seu carrinho está vazio.</p>';$('cartCount').textContent=`${count} ${count===1?'item':'itens'}`;$('cartHeaderTotal').textContent=money.format(total);$('cartTotal').textContent=money.format(total);$('cartButton').classList.toggle('has-items',count>0);localStorage.setItem('zuqui_cart',JSON.stringify([...cart]))}
const renderCartBase=renderCart;renderCart=function(){renderCartBase();if(!sending)$('reviewButton').textContent='Ler comanda e enviar'};
document.addEventListener('click',e=>{const add=e.target.closest('[data-add]'),dec=e.target.closest('[data-dec]'),cat=e.target.closest('[data-cat]');if(add){const p=data.products.find(x=>x.id===add.dataset.add);if(!p)return;const old=cart.get(p.id)||{...p,price:Number(p.source_price??p.price),qty:0};old.qty++;cart.set(p.id,old);renderCart();toast(`${old.qty} × ${p.name} no pedido`)}if(dec){const x=cart.get(dec.dataset.dec);if(x&&--x.qty<=0)cart.delete(x.id);renderCart()}if(cat){active=cat.dataset.cat;render();if(innerWidth<760)$('categoryTitle').scrollIntoView({behavior:'smooth',block:'center'})}});
document.addEventListener('click',e=>{const button=e.target.closest('[data-item-note]');if(!button)return;const item=cart.get(button.dataset.itemNote);if(!item)return;editingNoteId=item.id;$('itemNoteTitle').textContent=item.name;$('itemNoteText').value=item.observation||'';$('itemNoteCount').textContent=$('itemNoteText').value.length;$('itemNoteDialog').showModal();requestAnimationFrame(()=>$('itemNoteText').focus())});
$('itemNoteText').oninput=()=>{$('itemNoteCount').textContent=$('itemNoteText').value.length};$('closeItemNote').onclick=()=>$('itemNoteDialog').close();$('clearItemNote').onclick=()=>{$('itemNoteText').value='';$('itemNoteCount').textContent='0';$('itemNoteText').focus()};$('saveItemNote').onclick=()=>{const item=cart.get(editingNoteId);if(item){item.observation=$('itemNoteText').value.trim();cart.set(item.id,item);renderCart()}$('itemNoteDialog').close()};
function toggle(open){$('cart').classList.toggle('open',open);$('overlay').classList.toggle('open',open);$('cart').setAttribute('aria-hidden',String(!open))}$('cartButton').onclick=()=>toggle(true);$('closeCart').onclick=$('overlay').onclick=()=>toggle(false);
function tokenFrom(raw){let token='';try{const u=new URL(raw,location.origin);token=u.searchParams.get('claim')||''}catch{}if(!token&&/^[a-f0-9]{64}$/i.test(raw.trim()))token=raw.trim();if(!token)throw new Error('Este QR não é uma comanda válida do Zuqui.');return token}
async function acceptClaim(raw){const token=tokenFrom(raw);if(sending)return;$('scannerMessage').textContent='Validando comanda…';const result=await api('validate_card_claim',{card_claim:token});cardClaim=token;cardLabel=result.card_label;sessionStorage.setItem('zuqui_card_claim',token);sessionStorage.setItem('zuqui_card_label',cardLabel);stopScanner();updateIdentity();const continuation=afterScan;afterScan=null;if(continuation==='submit')return submitOrder();toast(`Comanda ${cardLabel} identificada`);if(continuation==='cart')toggle(true);if(continuation==='account')showAccount();if(continuation==='waiter')showWaiter()}
async function qrReader(){if(!qrReaderClass){const module=await import('https://esm.sh/@zxing/browser@0.1.5');qrReaderClass=module.BrowserQRCodeReader}return new qrReaderClass()}
async function startScanner(continuation=null){afterScan=continuation;$('scannerDialog').showModal();$('scannerMessage').textContent='Abrindo câmera…';try{const reader=await qrReader();scannerControls=await reader.decodeFromVideoDevice(undefined,$('scannerVideo'),result=>{if(result)acceptClaim(result.getText()).catch(e=>$('scannerMessage').textContent=e.message)});$('scannerMessage').textContent='Câmera ativa. Aponte para o QR da comanda.'}catch{$('scannerMessage').textContent='Não foi possível abrir a câmera. Permita o acesso ou escolha uma foto do QR.'}}
function stopScanner(){scannerControls?.stop();scannerControls=null;$('scannerVideo').srcObject?.getTracks().forEach(t=>t.stop());if($('scannerDialog').open)$('scannerDialog').close()}
$('closeScanner').onclick=stopScanner;$('scannerDialog').addEventListener('close',()=>{scannerControls?.stop();scannerControls=null});$('qrImage').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;const url=URL.createObjectURL(file);try{const reader=await qrReader(),result=await reader.decodeFromImageUrl(url);await acceptClaim(result.getText())}catch(err){$('scannerMessage').textContent=err.message||'Não foi possível reconhecer o QR nesta imagem.'}finally{URL.revokeObjectURL(url);e.target.value=''}};$('identifyCardButton').onclick=()=>startScanner();$('scanFromCart').onclick=()=>startScanner('cart');
function orderFingerprint(){return JSON.stringify([...cart.values()].map(x=>[x.id,x.qty,String(x.observation||'')]).sort())}
function showOrderResult(success,message='',secondFailure=false){const dialog=$('orderResultDialog');dialog.classList.toggle('success',success);dialog.classList.toggle('error',!success);$('orderResultIcon').textContent=success?'✓':'!';$('orderResultTitle').textContent=success?'PEDIDO ENVIADO':'PEDIDO NÃO ENVIADO';$('orderResultMessage').textContent=success?'':secondFailure?'Avise o atendente.':message;$('reviewFailedOrder').hidden=success||secondFailure;$('closeOrderResult').hidden=success||secondFailure;if(!dialog.open)dialog.showModal();if(success||secondFailure)setTimeout(()=>{if(dialog.open)dialog.close()},success?4000:6000)}
async function submitOrder(){if(sending)return;if(!cardClaim)return startScanner('submit');const fingerprint=orderFingerprint();sending=true;$('reviewButton').disabled=true;$('reviewButton').textContent='Enviando…';$('cartMessage').textContent='';try{const result=await api('create_order',{card_claim:cardClaim,reference_id:referenceId,note:$('orderNote').value,items:[...cart.values()].map(x=>({product_id:x.id,quantity:x.qty}))});let state=result;for(let attempt=0;attempt<30&&!['success','failed','uncertain'].includes(state.status);attempt++){await new Promise(resolve=>setTimeout(resolve,2000));state=await api('order_status',{guid:result.guid,receipt:result.receipt})}if(state.status==='success'){failedOrders.delete(fingerprint);toggle(false);showOrderResult(true);cart.clear();$('orderNote').value='';renderCart()}else{const attempts=(failedOrders.get(fingerprint)||0)+1;failedOrders.set(fingerprint,attempts);toggle(false);showOrderResult(false,state.error_message||'Revise o pedido e tente novamente.',attempts>=2)}}catch(e){const attempts=(failedOrders.get(fingerprint)||0)+1;failedOrders.set(fingerprint,attempts);toggle(false);showOrderResult(false,e.message||'Revise o pedido e tente novamente.',attempts>=2)}finally{sending=false;$('reviewButton').disabled=false;$('reviewButton').textContent='Lançar na comanda'}}
$('reviewButton').onclick=()=>{const ref=reference();if(!ref){$('cartMessage').textContent='Abra o cardápio pelo QR da mesa para definir o local da entrega.';return}if(!cart.size){$('cartMessage').textContent='Adicione pelo menos um produto ao pedido.';return}if(!data.ordering_enabled){$('cartMessage').textContent='Pedidos ainda não estão disponíveis.';return}$('cartMessage').textContent='';startScanner('submit')};
$('closeOrderResult').onclick=()=>$('orderResultDialog').close();$('reviewFailedOrder').onclick=()=>{$('orderResultDialog').close();$('reviewButton').textContent='Ler comanda e enviar';toggle(true)};
const updateIdentityBase=updateIdentity;updateIdentity=function(){updateIdentityBase();$('callWaiterButton').disabled=!(cardClaim||reference())};
async function showAccount(){if(!cardClaim)return startScanner('account');$('accountDialog').showModal();$('accountTitle').textContent=`Comanda ${cardLabel}`;$('accountContent').innerHTML='<p class="loading">Atualizando lançamentos…</p>';try{const a=await api('account_summary',{card_claim:cardClaim});$('accountContent').innerHTML=`<div class="account-total"><span>Total confirmado pelo cardápio digital</span><strong>${money.format(a.total)}</strong></div><div class="account-orders">${a.orders.map(o=>`<article><div><b>Pedido ${escape(o.order_number||'digital')}</b><small>${new Date(o.created_at).toLocaleString('pt-BR')}</small></div><strong>${money.format(o.total)}</strong></article>`).join('')||'<p>Nenhum lançamento digital confirmado nesta comanda.</p>'}</div><p class="account-disclaimer">Este valor inclui os pedidos confirmados por este cardápio. Consumos lançados diretamente no caixa ou pelo atendente podem não aparecer aqui; confirme o total final com a equipe.</p>`}catch(e){$('accountContent').innerHTML=`<p class="status-message error">${escape(e.message)}</p>`}}
$('accountButton').onclick=showAccount;$('closeAccount').onclick=()=>$('accountDialog').close();
function showWaiter(){if(!cardClaim)return startScanner('waiter');$('waiterMessage').textContent='';$('waiterDialog').showModal()}$('callWaiterButton').onclick=showWaiter;$('closeWaiter').onclick=()=>$('waiterDialog').close();document.querySelectorAll('[data-service]').forEach(button=>button.onclick=async()=>{document.querySelectorAll('[data-service]').forEach(x=>x.disabled=true);$('waiterMessage').className='message status-message';$('waiterMessage').textContent='Enviando solicitação…';try{const r=await api('create_service_request',{card_claim:cardClaim,reference_id:referenceId,request_type:button.dataset.service});$('waiterMessage').className='message status-message success';$('waiterMessage').textContent=r.already_open?'Já existe uma solicitação aberta. A equipe foi avisada.':'Solicitação enviada para a equipe.'}catch(e){$('waiterMessage').className='message status-message error';$('waiterMessage').textContent=e.message}finally{document.querySelectorAll('[data-service]').forEach(x=>x.disabled=false)}});
(async()=>{try{const urlClaim=params.get('claim');if(urlClaim){history.replaceState({},'',`${location.pathname}${referenceId?`?reference=${encodeURIComponent(referenceId)}`:''}`);await acceptClaim(urlClaim)}else if(cardClaim){try{const valid=await api('validate_card_claim',{card_claim:cardClaim});cardLabel=valid.card_label}catch{cardClaim='';cardLabel='';sessionStorage.removeItem('zuqui_card_claim');sessionStorage.removeItem('zuqui_card_label')}}data=await api('public_menu');render()}catch(e){$('notice').textContent=e.message;$('products').innerHTML='<div class="empty">Não foi possível carregar o cardápio agora.</div>';updateIdentity()}})();
