import QRCode from 'https://esm.sh/qrcode@1.5.4';
const cfg=window.ZUQUI_CARDAPIO_CONFIG||{};
let token=sessionStorage.getItem('zuqui_admin_token')||'',state={},tab='products';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(action,body={}){if(!cfg.apiUrl)throw new Error('Informe apiUrl em cardapio-config.js após implantar o servidor.');const r=await fetch(cfg.apiUrl,{method:'POST',headers:{'content-type':'application/json',...(token?{authorization:`Bearer ${token}`}:{})},body:JSON.stringify({action,...body})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Falha na operação.');return j}
async function load(){state=await api('admin_snapshot');$('loginView').hidden=true;$('appView').hidden=false;render()}
$('loginForm').onsubmit=async e=>{e.preventDefault();try{const r=await api('login',{username:$('username').value,password:$('password').value});token=r.access_token;sessionStorage.setItem('zuqui_admin_token',token);$('loginView').hidden=true;if(r.must_change_password)$('changeView').hidden=false;else await load()}catch(x){$('loginMsg').textContent=x.message}};
$('changeForm').onsubmit=async e=>{e.preventDefault();if($('newPassword').value!==$('confirmPassword').value)return $('changeMsg').textContent='As senhas não coincidem.';try{await api('change_password',{password:$('newPassword').value});$('changeView').hidden=true;await load()}catch(x){$('changeMsg').textContent=x.message}};
$('logout').onclick=()=>{token='';sessionStorage.clear();location.reload()};
$('tabs').onclick=e=>{const b=e.target.closest('[data-tab]');if(!b)return;tab=b.dataset.tab;document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));render()};
const list=(items,title,kind)=>`<div class="toolbar"><h2>${title}</h2><button data-new="${kind}">Adicionar</button></div><div class="grid">${items.map(x=>`<article class="item"><div><b>${esc(x.name||x.label||x.guid)}</b><p>${esc(x.description||x.status||'')}</p></div><div class="actions"><button data-edit="${kind}" data-id="${x.id}">Editar</button></div></article>`).join('')||'<p>Nenhum cadastro.</p>'}</div>`;
function render(){if(tab==='products')products();if(tab==='sync')syncPanel();if(tab==='cards')cards();if(tab==='references')references();if(tab==='orders')orders();if(tab==='integration')integration()}
function cards(){$('content').innerHTML=`<section class="card">${list(state.cards||[],'Comandas virtuais','card')}<p class="status">O QR usa um token aleatório de 256 bits. O número e o código virtual da comanda não ficam visíveis no QR.</p></section>`;document.querySelectorAll('[data-edit="card"]').forEach(b=>b.insertAdjacentHTML('afterend',`<button data-card-qr="${b.dataset.id}">Gerar QR seguro</button>`))}
function references(){$('content').innerHTML=`<section class="card">${list(state.references||[],'Pontos de referência','reference')}<p class="status">O QR da mesa abre o cardápio com este ponto de referência. Isso não vincula a referência à tabela Mesa do Raffinato.</p></section>`;document.querySelectorAll('[data-edit="reference"]').forEach(b=>b.insertAdjacentHTML('afterend',`<button data-reference-qr="${b.dataset.id}">Gerar QR da mesa</button>`))}
async function showQr(value,title){const d=$('qrDialog');$('qrTitle').textContent=title;$('qrImage').src=await QRCode.toDataURL(value,{width:420,margin:2,errorCorrectionLevel:'H'});$('qrValue').textContent=value;d.showModal()}
function products(){$('content').innerHTML=`<section class="card"><h2>Produtos</h2><div class="grid">${(state.products||[]).map(x=>`<article class="item"><div><b>${esc(x.source_name||x.name)}</b><p>${esc(x.description||'Sem descrição para o cliente')}</p><strong>R$ ${Number(x.source_price??x.price).toFixed(2).replace('.',',')}</strong><p class="source">Raffinato: ${esc(x.store_key||'-')} · produto ${esc(x.raffinato_product_id||'-')} · atualizado ${x.source_updated_at?new Date(x.source_updated_at).toLocaleString('pt-BR'):'-'}</p><p>${x.visible?'Visível':'Oculto'} · ${x.featured?'Destaque':'Comum'} · ${x.source_available?'Disponível na origem':'Indisponível na origem'}</p></div><div class="actions"><button data-edit="product" data-id="${x.id}">Editar apresentação</button></div></article>`).join('')||'<p>Nenhum produto sincronizado.</p>'}</div><hr>${list(state.categories||[],'Categorias exibidas','category')}</section>`}
function syncPanel(){const s=state.catalog_sync||{},r=(s.runs||[])[0];$('content').innerHTML=`<section class="card"><div class="toolbar"><h2>Sincronização do Raffinato</h2><button id="syncNow">Sincronizar agora</button></div><p class="status ${s.connector?.active?'ok':'bad'}">${s.connector?.active?`Conector ativo. Último contato: ${s.connector.last_seen_at?new Date(s.connector.last_seen_at).toLocaleString('pt-BR'):'ainda não ocorreu'}.`:'O serviço local ainda não foi cadastrado ou conectado.'}</p><p>Última execução: ${r?`${new Date(r.started_at).toLocaleString('pt-BR')} · ${esc(r.status)} · ${r.processed} produtos processados`:'nenhuma'}.</p>${r?.error_message?`<p class="status bad">${esc(r.error_message)}</p>`:''}<div class="grid">${(s.runs||[]).map(x=>`<article class="item"><div><b>${new Date(x.started_at).toLocaleString('pt-BR')} · ${esc(x.status)}</b><p>${x.processed} processados · modo ${esc(x.mode)}<br>${esc(x.error_message||'')}</p></div></article>`).join('')}</div></section>`;$('syncNow').onclick=async()=>{await api('catalog_sync_request',{store_key:s.connector?.store_key||'zuqui-filial-1'});alert('Solicitação registrada. O serviço da loja iniciará em até 30 segundos.');await load()}}
function orders(){$('content').innerHTML=`<section class="card"><div class="toolbar"><h2>Pedidos e retornos</h2><button id="refresh">Atualizar</button></div><div class="grid">${(state.orders||[]).map(o=>`<article class="item"><div><b>${esc(o.status)} · ${new Date(o.created_at).toLocaleString('pt-BR')}</b><p class="order-meta">GUID ${esc(o.guid)}<br>Comanda ${esc(o.card_label)} · Referência ${esc(o.reference_name)}<br>idvenda ${esc(o.idvenda||'-')} · numeropedido ${esc(o.numeropedido||'-')}<br>${esc(o.error_message||'')}</p></div></article>`).join('')||'<p>Nenhum pedido.</p>'}</div></section>`}
function integration(){const i=state.integration||{};$('content').innerHTML=`<section class="card"><h2>Integração de pedidos Raffinato</h2><p class="status ${i.ready?'ok':'bad'}">${i.ready?'Configuração técnica completa. Pedidos públicos continuam dependendo de ativação explícita.':'Faltam URL completa/porta, método HTTP, autenticação e conectividade com a rede privada.'}</p><p>A sincronização do catálogo é independente deste envio de pedidos.</p><div class="form-grid"><label class="wide">URL completa da rota /RecebePedidos<input id="endpoint" value="${esc(i.endpoint_url)}" placeholder="Não conhecida"></label><label>Método HTTP<input id="method" value="${esc(i.http_method)}" placeholder="Não conhecido"></label><label>Tipo de autenticação<input id="authType" value="${esc(i.auth_type)}" placeholder="Não conhecido"></label><label class="wide">Observações<textarea id="notes">${esc(i.notes)}</textarea></label></div><button id="saveIntegration">Salvar informações não secretas</button><hr><section class="card test"><h3>Primeiro teste controlado</h3><p>Comanda 4 · MESA 04 · garçom 20 · produto 451 · R$ 6,70.</p><button id="testOrder" ${i.ready?'':'disabled'}>Enviar um único pedido de teste</button><p id="testMsg"></p></section><hr><label><input id="enabled" type="checkbox" ${state.ordering_enabled?'checked':''} ${i.test_validated?'':'disabled'}> Habilitar pedidos públicos</label></section>`;$('saveIntegration').onclick=saveIntegration;$('testOrder').onclick=testOrder;$('enabled').onchange=async e=>{await api('set_ordering',{enabled:e.target.checked});await load()}}
async function saveIntegration(){await api('save_integration',{endpoint_url:$('endpoint').value,http_method:$('method').value,auth_type:$('authType').value,notes:$('notes').value});await load()}
async function testOrder(){if(!confirm('Enviar agora o pedido único de teste para a comanda 4?'))return;try{$('testOrder').disabled=true;const r=await api('test_order');$('testMsg').textContent=`Resultado: ${r.status}. ${r.message||''}`;await load()}catch(e){$('testMsg').textContent=e.message}}
document.addEventListener('click',async e=>{if(e.target.id==='refresh')await load();if(e.target.dataset.referenceQr){const x=(state.references||[]).find(v=>v.id===e.target.dataset.referenceQr);return showQr(`${location.origin}/cardapio/?reference=${encodeURIComponent(x.id)}`,`Mesa / referência ${x.name}`)}if(e.target.dataset.cardQr){const x=(state.cards||[]).find(v=>v.id===e.target.dataset.cardQr),r=await api('generate_card_claim',{card_id:x.id});return showQr(`${location.origin}/cardapio/?claim=${encodeURIComponent(r.token)}`,`Comanda ${x.label}`)}const kind=e.target.dataset.new||e.target.dataset.edit;if(!kind)return;const current=(state[kind+'s']||state.categories||[]).find(x=>x.id===e.target.dataset.id)||{};if(kind==='product'){await api('upsert_entity',{kind,id:current.id,description:prompt('Descrição para o cliente',current.description||'')||'',image_url:prompt('URL da foto',current.image_url||'')||'',category_id:prompt('ID da categoria exibida',current.category_id||'')||null,sort_order:Number(prompt('Ordem de exibição',current.sort_order||0)||0),featured:confirm('Marcar como destaque?'),visible:confirm('Exibir no cardápio?')});return load()}const name=prompt(`Nome de ${kind}`,current.name||current.label||'');if(!name)return;await api('upsert_entity',{kind,id:current.id,name,label:name,available:true,sort_order:Number(current.sort_order||0)});await load()});
if(token)load().catch(()=>{token='';sessionStorage.clear()});
