alter table menu_products add column if not exists store_key text;
alter table menu_products add column if not exists raffinato_product_id bigint;
alter table menu_products add column if not exists source_name text;
alter table menu_products add column if not exists source_price numeric(12,2);
alter table menu_products add column if not exists source_barcode text;
alter table menu_products add column if not exists source_unit text;
alter table menu_products add column if not exists source_category_id bigint;
alter table menu_products add column if not exists source_category_name text;
alter table menu_products add column if not exists source_category_tree text;
alter table menu_products add column if not exists source_available boolean not null default true;
alter table menu_products add column if not exists source_updated_at timestamptz;
alter table menu_products add column if not exists source_sync_run_id uuid;
alter table menu_products add column if not exists featured boolean not null default false;
alter table menu_products add column if not exists visible boolean not null default false;
create unique index if not exists menu_products_store_raffinato_uidx on menu_products(store_key,raffinato_product_id);
create table if not exists menu_catalog_connectors(id uuid primary key default gen_random_uuid(),store_key text unique not null,token_hash text unique not null,active boolean not null default true,created_at timestamptz not null default now(),last_seen_at timestamptz);
create table if not exists menu_catalog_sync_runs(id uuid primary key default gen_random_uuid(),store_key text not null,mode text not null,status text not null default 'running',processed int not null default 0,changed int not null default 0,error_message text,started_at timestamptz not null default now(),finished_at timestamptz);
create table if not exists menu_catalog_sync_requests(id uuid primary key default gen_random_uuid(),store_key text not null,status text not null default 'pending',requested_at timestamptz not null default now(),started_at timestamptz,finished_at timestamptz,error_message text);
create table if not exists menu_card_claims(id uuid primary key default gen_random_uuid(),card_id uuid not null references menu_cards(id) on delete cascade,token_hash text unique not null,active boolean not null default true,created_at timestamptz not null default now(),last_used_at timestamptz);
create or replace function increment_catalog_sync_processed(run_uuid uuid,amount int) returns void language sql security definer set search_path=public as $$ update menu_catalog_sync_runs set processed=processed+amount,changed=changed+amount where id=run_uuid $$;
revoke all on function increment_catalog_sync_processed(uuid,int) from public,anon,authenticated;
alter table menu_catalog_connectors enable row level security;alter table menu_catalog_sync_runs enable row level security;alter table menu_catalog_sync_requests enable row level security;
alter table menu_card_claims enable row level security;
revoke all on menu_catalog_connectors,menu_catalog_sync_runs,menu_catalog_sync_requests,menu_card_claims from anon,authenticated;
